sudo: required
language: rust
rust:
    - nightly
dist: xenial
notifications:
  email: false
matrix:
  include:
    - rust: nightly
env:
    - SYSTEM_CARGO=1
script:
  - cargo build
  - cargo doc --all --document-private-items
before_deploy:
  - cargo doc --all --document-private-items
  - echo '<meta http-equiv=refresh content=0;url=lists/index.html>' > target/doc/index.html
  - mkdir public
  - cp -r target/doc public/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public
  on:
    branch: master
